# Generated by Django 3.1.6 on 2021-02-24 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0002_auto_20210222_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название')),
                ('price', models.SmallIntegerField(blank=True, null=True, verbose_name='Цена, руб.')),
                ('published_date', models.DateField(blank=True, null=True, verbose_name='Год издания')),
                ('page_numbers', models.SmallIntegerField(blank=True, null=True, verbose_name='Количество страниц')),
                ('binding', models.CharField(blank=True, max_length=80, null=True, verbose_name='Переплет')),
                ('book_format', models.CharField(blank=True, max_length=80, null=True, verbose_name='Формат')),
                ('isbn_num', models.CharField(blank=True, max_length=80, null=True, verbose_name='ISBN')),
                ('weight', models.SmallIntegerField(blank=True, null=True, verbose_name='Вес, г.')),
                ('age_restriction', models.SmallIntegerField(blank=True, null=True, verbose_name='Возрастные ограничения')),
                ('available_number', models.SmallIntegerField(blank=True, null=True, verbose_name='В наличии, шт.')),
                ('is_available', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Да', max_length=80, verbose_name='Доступнны для заказа')),
                ('rate', models.SmallIntegerField(blank=True, null=True, verbose_name='Рейтинг')),
                ('creation_date', models.DateField(blank=True, null=True, verbose_name='Дата внесения в каталог')),
                ('last_modifyed', models.DateField(blank=True, null=True, verbose_name='Дата последнего изменения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.author', verbose_name='Автор')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.genre', verbose_name='Жанр')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Книги', to='dictionaries.publisher', verbose_name='Издательство')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.bookseries', verbose_name='Серия')),
            ],
        ),
    ]
