# Generated by Django 3.1.6 on 2021-02-24 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20210222_2210'),
        ('books', '0002_auto_20210224_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dictionaries.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.genre', verbose_name='Жанр'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='series',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='dictionaries.bookseries', verbose_name='Серия'),
            preserve_default=False,
        ),
    ]
