# Generated by Django 3.1.6 on 2021-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0002_auto_20210222_2210'),
        ('books', '0004_auto_20210224_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(to='dictionaries.Genre', verbose_name='Жанр'),
        ),
    ]
