# Generated by Django 3.1.6 on 2021-02-28 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20210224_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_picture',
            field=models.ImageField(default='dsdf', upload_to='uploads/', verbose_name='Обложка'),
            preserve_default=False,
        ),
    ]
