# Generated by Django 3.1.6 on 2021-03-01 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_book_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='age_restriction',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='available_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='В наличии, шт.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='page_numbers',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество страниц'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Цена, руб.'),
        ),
        migrations.AlterField(
            model_name='book',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='book',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Вес, г.'),
        ),
    ]
