# Generated by Django 3.1.6 on 2021-03-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_auto_20210302_0028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='last_modifyed',
        ),
        migrations.AddField(
            model_name='book',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дата последнего изменения'),
        ),
        migrations.AlterField(
            model_name='book',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата внесения в каталог'),
        ),
    ]
