# Generated by Django 3.1.6 on 2021-03-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20210302_1900'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='creation_date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='last_updated',
            new_name='updated',
        ),
    ]
