# Generated by Django 3.1.6 on 2021-03-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20210303_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год издания'),
        ),
    ]
