# Generated by Django 3.1.5 on 2021-01-31 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=80, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=80, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=80, null=True, verbose_name='Отчество')),
                ('country', models.CharField(blank=True, max_length=80, null=True, verbose_name='Страна')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('birthdate', models.DateField(blank=True, default=datetime.date(1970, 1, 1), null=True, verbose_name='Дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='BookSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(max_length=80, verbose_name='Серия')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=80, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher_name', models.CharField(max_length=80, verbose_name='Издательство')),
                ('publisher_description', models.TextField(verbose_name='Описание')),
            ],
        ),
    ]
