# Generated by Django 3.1.6 on 2021-03-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210309_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookincart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Колечество товара'),
        ),
    ]
