# Generated by Django 3.1.6 on 2021-03-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210313_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookincart',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Цена, руб.'),
        ),
    ]
