# Generated by Django 3.1.6 on 2021-03-06 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес доставки')),
                ('telephone_number', models.CharField(max_length=15, verbose_name='Контактный номер')),
                ('customer_comments', models.TextField(blank=True, null=True, verbose_name='Комментарии к заказу')),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='carts.cart', verbose_name='Корзина пользователя')),
            ],
        ),
    ]
