# Generated by Django 3.1.6 on 2021-03-20 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210319_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В обработке', 'В обработке'), ('Закрытый', 'Закрытый'), ('Отменен', 'Отменен')], default='Новый', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
