# Generated by Django 3.1.6 on 2021-03-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20210320_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Новый', 'Новый'), ('В обработке', 'В обработке'), ('Закрыт', 'Закрыт'), ('Отменен', 'Отменен')], default='Новый', max_length=20, verbose_name='Статус заказа'),
        ),
    ]
